import { ProductCategory, StorePreset } from '../types';

export const STORE_PRESETS: StorePreset[] = [
  {
    id: 'amazon',
    name: 'Amazon',
    defaultReturnDays: 30,
    defaultWarrantyMonths: 12,
    badgeBg: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    badgeText: 'Amazon',
    returnPolicySummary: '30-day standard return window on most shipped items.',
    policyUrl: 'https://www.amazon.com/gp/help/customer/display.html?nodeId=GKM69DUUYKQWKWX7',
  },
  {
    id: 'apple',
    name: 'Apple',
    defaultReturnDays: 14,
    defaultWarrantyMonths: 12,
    badgeBg: 'bg-zinc-500/10 text-zinc-300 border-zinc-500/20',
    badgeText: 'Apple',
    returnPolicySummary: '14 calendar days from receipt date. 1-year standard AppleCare warranty.',
    policyUrl: 'https://www.apple.com/shop/help/returns_refund',
  },
  {
    id: 'bestbuy',
    name: 'Best Buy',
    defaultReturnDays: 15,
    defaultWarrantyMonths: 12,
    badgeBg: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    badgeText: 'Best Buy',
    returnPolicySummary: '15-day return window (60 days for My Best Buy Plus/Total members).',
    policyUrl: 'https://www.bestbuy.com/site/help-topics/return-exchange-policy/pcmcat260800050014.c',
  },
  {
    id: 'target',
    name: 'Target',
    defaultReturnDays: 90,
    defaultWarrantyMonths: 12,
    badgeBg: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
    badgeText: 'Target',
    returnPolicySummary: '90 days for most unopened items (extra 30 days with Target RedCard).',
    policyUrl: 'https://help.target.com/help/subcategoryarticle?childcat=Returns',
  },
  {
    id: 'walmart',
    name: 'Walmart',
    defaultReturnDays: 90,
    defaultWarrantyMonths: 12,
    badgeBg: 'bg-sky-500/10 text-sky-400 border-sky-500/20',
    badgeText: 'Walmart',
    returnPolicySummary: '90 days standard return window (30 days for electronics/drones).',
    policyUrl: 'https://www.walmart.com/help/article/walmart-standard-return-policy/adc007b8b40842bb8454b5dfaebc1955',
  },
  {
    id: 'costco',
    name: 'Costco',
    defaultReturnDays: 90,
    defaultWarrantyMonths: 24,
    badgeBg: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    badgeText: 'Costco',
    returnPolicySummary: 'Generous 100% satisfaction guarantee (90 days for major electronics).',
    policyUrl: 'https://customerservice.costco.com/app/answers/detail/a_id/1191',
  },
  {
    id: 'nordstrom',
    name: 'Nordstrom',
    defaultReturnDays: 365,
    defaultWarrantyMonths: 0,
    badgeBg: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    badgeText: 'Nordstrom',
    returnPolicySummary: 'Case-by-case philosophy, generally up to 365 days with receipt.',
  },
  {
    id: 'homedepot',
    name: 'The Home Depot',
    defaultReturnDays: 90,
    defaultWarrantyMonths: 12,
    badgeBg: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
    badgeText: 'Home Depot',
    returnPolicySummary: '90 days with valid receipt (30 days for area rugs and select tools).',
  },
  {
    id: 'ikea',
    name: 'IKEA',
    defaultReturnDays: 365,
    defaultWarrantyMonths: 120,
    badgeBg: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    badgeText: 'IKEA',
    returnPolicySummary: '365 days for unopened items, 180 days for opened items.',
  },
  {
    id: 'bhphoto',
    name: 'B&H Photo Video',
    defaultReturnDays: 30,
    defaultWarrantyMonths: 12,
    badgeBg: 'bg-teal-500/10 text-teal-400 border-teal-500/20',
    badgeText: 'B&H Photo',
    returnPolicySummary: '30 days for most unused/unopened equipment.',
  },
  {
    id: 'other',
    name: 'Other Store',
    defaultReturnDays: 30,
    defaultWarrantyMonths: 12,
    badgeBg: 'bg-gray-500/10 text-gray-400 border-gray-500/20',
    badgeText: 'Retailer',
    returnPolicySummary: 'Custom return policy. Please specify days according to receipt.',
  }
];

export const CATEGORIES: ProductCategory[] = [
  'Electronics',
  'Computers & Office',
  'Clothing & Apparel',
  'Home & Kitchen',
  'Furniture',
  'Appliances',
  'Sports & Outdoors',
  'Toys & Games',
  'Beauty & Health',
  'Other'
];

export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar ($)' },
  { code: 'EUR', symbol: '€', name: 'Euro (€)' },
  { code: 'GBP', symbol: '£', name: 'British Pound (£)' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee (₹)' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar (C$)' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar (A$)' },
];
